name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore explore-cebu-maui/CebuFinalApp/CebuFinalApp.csproj

      - name: Build and Publish APK
        # Added /p:CheckEolWorkloads=false to bypass the "out of support" error
        run: dotnet publish explore-cebu-maui/CebuFinalApp/CebuFinalApp.csproj -f net8.0-android -c Release /p:CheckEolWorkloads=false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExploreCebu-Android-Build
          path: explore-cebu-maui/CebuFinalApp/bin/Release/net8.0-android/*-Signed.apk