name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: windows-latest
    # This forces GitHub to 'stay' in the folder where your code is
    defaults:
      run:
        working-directory: CebuFinalApp 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Restore Dependencies
        run: dotnet restore CebuFinalApp.csproj

      - name: Build and Publish APK
        run: dotnet publish CebuFinalApp.csproj -f net8.0-android -c Release /p:CheckEolWorkloads=false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExploreCebu-Android-Build
          # This path is relative to the working-directory
          path: bin/Release/net8.0-android/*-Signed.apk